# Generated by Django 5.0.4 on 2024-05-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='size_object',
            new_name='color_object',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_object',
            new_name='color_object',
        ),
    ]
